# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-14 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=200)),
                ('form_id', models.CharField(max_length=200)),
                ('barcode', models.CharField(max_length=200)),
                ('cordinates', models.CharField(max_length=200)),
            ],
        ),
    ]
